[package]
name = "catpaw-bindings-boa"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "CatPaw browser engine: bindings-boa"

[dependencies]
boa_engine = { workspace = true, features = ["annex-b", "intl_bundled"] }
boa_gc.workspace = true
catpaw-dom = { path = "../catpaw-dom", version = "0.1.0" }
catpaw-js = { path = "../catpaw-js", version = "0.1.0" }
catpaw-js-boa = { path = "../catpaw-js-boa", version = "0.1.0" }
catpaw-web = { path = "../catpaw-web", version = "0.1.0" }
url.workspace = true

[dev-dependencies]
catpaw-dom = { path = "../catpaw-dom", version = "0.1.0" }
png.workspace = true
