//! Code emitters.
//!
//! [`emit_web`] produces the engine-neutral side: `InterfaceId`, the IDL
//! enums, dictionaries and unions as Rust types, and one `XImpl` trait per
//! interface listing exactly the functions the glue calls.
//!
//! [`emit_boa`] produces the Boa glue: one native function per attribute
//! accessor and operation, conversions for the generated types, and static
//! tables the runtime installs into a realm.

use std::fmt::Write as _;

use crate::model::{ConstValue, DefaultValue, Idl, InterfaceKind, Type};
use crate::names::{lit, snake, variant};
use crate::plan::{
    AttrKind, Handle, Manifest, Named, PArg, PAttr, PInterface, POp, POverload, Plan, Planner,
    ReflectKind, Stringifier, TraitMember,
};

macro_rules! w {
    ($out:expr, $($arg:tt)*) => {
        writeln!($out, $($arg)*).unwrap()
    };
}

const HEADER: &str = "// @generated by `cargo xtask bindgen` from the Web IDL corpus in\n// crates/catpaw-webidl/idl and crates/catpaw-webidl/bindings.toml.\n// Do not edit by hand; edit the manifest or the emitters and regenerate.\n";

#[derive(Clone, Copy, PartialEq, Eq)]
enum Pos {
    Arg,
    Ret,
}

pub struct Emitter<'a> {
    idl: &'a Idl,
    plan: &'a Plan,
    types: Planner<'a>,
}

impl<'a> Emitter<'a> {
    pub fn new(idl: &'a Idl, manifest: &'a Manifest, plan: &'a Plan) -> Self {
        Self {
            idl,
            plan,
            types: Planner::new(idl, manifest),
        }
    }

    fn rust_type(&self, ty: &Type, pos: Pos) -> String {
        match ty {
            Type::Any | Type::Object => "Value".into(),
            Type::Undefined => "()".into(),
            Type::Boolean => "bool".into(),
            Type::Byte => "i8".into(),
            Type::Octet => "u8".into(),
            Type::Short => "i16".into(),
            Type::UnsignedShort => "u16".into(),
            Type::Long => "i32".into(),
            Type::UnsignedLong => "u32".into(),
            Type::LongLong => "i64".into(),
            Type::UnsignedLongLong => "u64".into(),
            Type::Float | Type::Double => "f64".into(),
            Type::DomString | Type::UsvString | Type::ByteString => "String".into(),
            Type::ArrayBuffer => match pos {
                Pos::Arg => "Vec<u8>".into(),
                Pos::Ret => "ArrayBufferData".into(),
            },
            Type::BufferLike(_) => match pos {
                Pos::Arg => "Vec<u8>".into(),
                Pos::Ret => "Uint8ArrayData".into(),
            },
            Type::Symbol => "Value".into(),
            Type::Named(n) => match self.types.classify(n) {
                Named::Node => "NodeId".into(),
                Named::Object => "ObjectId".into(),
                Named::Window => "WindowRef".into(),
                Named::EventTarget => "EventTargetRef".into(),
                Named::Dictionary | Named::Enum => n.clone(),
                Named::Callback | Named::CallbackInterface => "Callback".into(),
                Named::Unknown => "Value".into(),
            },
            Type::Sequence(t) | Type::FrozenArray(t) => format!("Vec<{}>", self.rust_type(t, pos)),
            Type::Record(_, v) => format!("Vec<(String, {})>", self.rust_type(v, pos)),
            Type::Promise(_) => "PromiseRef".into(),
            Type::Union(_) => self.types.type_label(ty),
            Type::Nullable(t) => match **t {
                Type::Any | Type::Object => "Value".into(),
                _ => format!("Option<{}>", self.rust_type(t, pos)),
            },
        }
    }

    /// The Rust type of an argument as it appears in a trait signature.
    fn arg_type(&self, a: &PArg) -> String {
        let base = self.rust_type(&a.ty, Pos::Arg);
        if a.variadic {
            return format!("Vec<{base}>");
        }
        if a.optional && a.default.is_none() {
            return match &a.ty {
                Type::Any | Type::Object => base,
                Type::Nullable(_) => base,
                Type::Named(n) if self.types.classify(n) == Named::Dictionary => base,
                _ => format!("Option<{base}>"),
            };
        }
        base
    }

    fn this_param(handle: Handle) -> &'static str {
        match handle {
            Handle::Node => ", this: NodeId",
            Handle::Object => ", this: ObjectId",
            Handle::EventTarget => ", this: EventTargetRef",
            Handle::Window => "",
        }
    }

    fn sig_args(&self, o: &POverload) -> String {
        o.args
            .iter()
            .map(|a| format!(", {}: {}", a.rust, self.arg_type(a)))
            .collect()
    }

    fn special_ret(&self, ty: &Type) -> String {
        match ty {
            Type::Nullable(inner) => format!("Option<{}>", self.rust_type(inner, Pos::Ret)),
            other => format!("Option<{}>", self.rust_type(other, Pos::Ret)),
        }
    }

    // ---------------------------------------------------------------- web

    pub fn emit_web(&self) -> String {
        let mut out = String::new();
        out.push_str(HEADER);
        out.push_str(
            "#![allow(clippy::too_many_arguments, clippy::type_complexity, clippy::upper_case_acronyms, clippy::enum_variant_names, clippy::large_enum_variant, non_camel_case_types, unused_imports)]\n\n",
        );
        out.push_str("use catpaw_js::{ArrayBufferData, Callback, EventTargetRef, Fallible, NodeId, ObjectId, PromiseRef, Uint8ArrayData, Value, WindowRef};\n\nuse crate::Cx;\n\n");

        self.emit_interface_id(&mut out);
        for name in &self.plan.enums {
            self.emit_enum(&mut out, name);
        }
        for name in &self.plan.dictionaries {
            self.emit_dictionary(&mut out, name);
        }
        for u in &self.plan.unions {
            w!(out, "#[derive(Clone, Debug)]\npub enum {} {{", u.name);
            for m in &u.members {
                w!(
                    out,
                    "    {}({}),",
                    self.types.type_label(m),
                    self.rust_type(m, Pos::Arg)
                );
            }
            w!(out, "}}\n");
        }
        for iface in self
            .plan
            .mixins
            .iter()
            .chain(&self.plan.interfaces)
            .chain(&self.plan.namespaces)
        {
            self.emit_trait(&mut out, iface);
        }
        out
    }

    fn emit_interface_id(&self, out: &mut String) {
        let names: Vec<&str> = self
            .plan
            .interfaces
            .iter()
            .map(|i| i.name.as_str())
            .collect();
        w!(
            out,
            "/// Every interface that has bindings, parents before children."
        );
        w!(
            out,
            "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord)]\n#[repr(u16)]\npub enum InterfaceId {{"
        );
        for n in &names {
            w!(out, "    {n},");
        }
        w!(out, "}}\n");
        w!(out, "impl InterfaceId {{");
        w!(out, "    pub const COUNT: usize = {};", names.len());
        w!(out, "    pub const ALL: [InterfaceId; {}] = [", names.len());
        for n in &names {
            w!(out, "        InterfaceId::{n},");
        }
        w!(out, "    ];\n");
        w!(
            out,
            "    pub fn name(self) -> &'static str {{\n        match self {{"
        );
        for n in &names {
            w!(out, "            InterfaceId::{n} => {},", lit(n));
        }
        w!(out, "        }}\n    }}\n");
        w!(
            out,
            "    pub fn from_name(name: &str) -> Option<InterfaceId> {{\n        Some(match name {{"
        );
        for n in &names {
            w!(out, "            {} => InterfaceId::{n},", lit(n));
        }
        w!(out, "            _ => return None,\n        }})\n    }}\n");
        w!(
            out,
            "    pub fn parent(self) -> Option<InterfaceId> {{\n        match self {{"
        );
        for i in &self.plan.interfaces {
            match &i.parent {
                Some(p) => w!(
                    out,
                    "            InterfaceId::{} => Some(InterfaceId::{p}),",
                    i.name
                ),
                None => w!(out, "            InterfaceId::{} => None,", i.name),
            }
        }
        w!(out, "        }}\n    }}\n");
        w!(
            out,
            "    /// Whether this interface is `ancestor` or inherits from it.\n    pub fn is_a(self, ancestor: InterfaceId) -> bool {{\n        let mut cur = Some(self);\n        while let Some(i) = cur {{\n            if i == ancestor {{\n                return true;\n            }}\n            cur = i.parent();\n        }}\n        false\n    }}\n"
        );
        w!(
            out,
            "    /// The element interface for an HTML local name.\n    pub fn for_html_tag(local: &str) -> Option<InterfaceId> {{\n        Some(match local {{"
        );
        for (tag, iface) in &self.plan.tags {
            if names.contains(&iface.as_str()) {
                w!(out, "            {} => InterfaceId::{iface},", lit(tag));
            }
        }
        w!(
            out,
            "            _ => return None,\n        }})\n    }}\n}}\n"
        );
    }

    fn emit_enum(&self, out: &mut String, name: &str) {
        let e = &self.idl.enums[name];
        w!(
            out,
            "#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash)]\npub enum {name} {{"
        );
        for v in &e.values {
            w!(out, "    {},", variant(v));
        }
        w!(out, "}}\n\nimpl {name} {{");
        w!(
            out,
            "    pub fn as_str(self) -> &'static str {{\n        match self {{"
        );
        for v in &e.values {
            w!(out, "            {name}::{} => {},", variant(v), lit(v));
        }
        w!(out, "        }}\n    }}\n");
        w!(
            out,
            "    pub fn parse(s: &str) -> Option<Self> {{\n        Some(match s {{"
        );
        for v in &e.values {
            w!(out, "            {} => {name}::{},", lit(v), variant(v));
        }
        w!(
            out,
            "            _ => return None,\n        }})\n    }}\n}}\n"
        );
    }

    /// Members of a dictionary including inherited ones, parents first.
    fn dictionary_members(&self, name: &str) -> Vec<(String, Type, bool, Option<DefaultValue>)> {
        let mut chain = Vec::new();
        let mut cur = Some(name.to_string());
        while let Some(n) = cur {
            let Some(d) = self.idl.dictionaries.get(&n) else {
                break;
            };
            chain.push(d);
            cur = d.parent.clone();
        }
        let mut out = Vec::new();
        for d in chain.into_iter().rev() {
            for m in &d.members {
                if let Some(ty) = self.types.prune(&self.idl.resolve(&m.ty)) {
                    out.push((m.name.clone(), ty, m.required, m.default.clone()));
                }
            }
        }
        out
    }

    fn dict_field_type(&self, ty: &Type, required: bool, default: &Option<DefaultValue>) -> String {
        let base = self.rust_type(ty, Pos::Arg);
        let is_dict = matches!(ty, Type::Named(n) if self.types.classify(n) == Named::Dictionary);
        if required
            || default.is_some()
            || is_dict
            || matches!(ty, Type::Any | Type::Object | Type::Nullable(_))
        {
            base
        } else {
            format!("Option<{base}>")
        }
    }

    fn emit_dictionary(&self, out: &mut String, name: &str) {
        w!(out, "#[derive(Clone, Debug)]\npub struct {name} {{");
        for (n, ty, required, default) in self.dictionary_members(name) {
            w!(
                out,
                "    pub {}: {},",
                snake(&n),
                self.dict_field_type(&ty, required, &default)
            );
        }
        w!(out, "}}\n");
    }

    fn emit_trait(&self, out: &mut String, iface: &PInterface) {
        if iface.trait_members.is_empty() {
            return;
        }
        let this = Self::this_param(iface.handle);
        w!(out, "pub trait {}Impl {{", iface.name);
        for m in &iface.trait_members {
            match m {
                TraitMember::Getter {
                    rust,
                    ty,
                    is_static,
                } => {
                    let this = if *is_static { "" } else { this };
                    w!(
                        out,
                        "    fn {rust}(cx: &mut Cx<'_>{this}) -> Fallible<{}>;",
                        self.rust_type(ty, Pos::Ret)
                    );
                }
                TraitMember::Setter {
                    rust,
                    ty,
                    is_static,
                } => {
                    let this = if *is_static { "" } else { this };
                    w!(
                        out,
                        "    fn set_{}(cx: &mut Cx<'_>{this}, value: {}) -> Fallible<()>;",
                        rust.trim_end_matches('_'),
                        self.rust_type(ty, Pos::Arg)
                    );
                }
                TraitMember::Op {
                    overload,
                    is_static,
                } => {
                    let this = if *is_static || iface.kind == InterfaceKind::Namespace {
                        ""
                    } else {
                        this
                    };
                    w!(
                        out,
                        "    fn {}(cx: &mut Cx<'_>{this}{}) -> Fallible<{}>;",
                        overload.rust,
                        self.sig_args(overload),
                        self.rust_type(&overload.ret, Pos::Ret)
                    );
                }
                TraitMember::Constructor { overload } => {
                    w!(
                        out,
                        "    fn {}(cx: &mut Cx<'_>{}) -> Fallible<{}>;",
                        overload.rust,
                        self.sig_args(overload),
                        self.rust_type(&overload.ret, Pos::Ret)
                    );
                }
                TraitMember::IndexedGet { ty } => {
                    w!(
                        out,
                        "    fn indexed_get(cx: &mut Cx<'_>{this}, index: u32) -> Fallible<{}>;",
                        self.special_ret(ty)
                    );
                }
                TraitMember::NamedGet { ty } => {
                    w!(
                        out,
                        "    fn named_get(cx: &mut Cx<'_>{this}, name: &str) -> Fallible<{}>;",
                        self.special_ret(ty)
                    );
                }
                TraitMember::NamedProperties => {
                    w!(
                        out,
                        "    fn named_properties(cx: &mut Cx<'_>{this}) -> Fallible<Vec<String>>;"
                    );
                }
                TraitMember::NamedSet { ty } => {
                    w!(
                        out,
                        "    fn named_set(cx: &mut Cx<'_>{this}, name: &str, value: {}) -> Fallible<()>;",
                        self.rust_type(ty, Pos::Arg)
                    );
                }
                TraitMember::NamedDelete => {
                    w!(
                        out,
                        "    fn named_delete(cx: &mut Cx<'_>{this}, name: &str) -> Fallible<bool>;"
                    );
                }
                TraitMember::Iterate { key, value } => {
                    w!(
                        out,
                        "    fn iterate(cx: &mut Cx<'_>{this}) -> Fallible<Vec<({}, {})>>;",
                        self.rust_type(key, Pos::Ret),
                        self.rust_type(value, Pos::Ret)
                    );
                }
                TraitMember::Stringify => {
                    w!(
                        out,
                        "    fn stringify(cx: &mut Cx<'_>{this}) -> Fallible<String>;"
                    );
                }
            }
        }
        w!(out, "}}\n");
    }

    // ---------------------------------------------------------------- boa

    /// An expression converting the `&JsValue` named by `v` to the Rust type
    /// of `ty`. May use `?` and expects `ctx` in scope.
    fn conv(&self, ty: &Type, v: &str, null_to_empty: bool) -> String {
        match ty {
            Type::Any | Type::Object | Type::Symbol => format!("rt::value_from_js({v}, ctx)?"),
            Type::Undefined => "()".into(),
            Type::Boolean => format!("{v}.to_boolean()"),
            Type::Byte => format!("{v}.to_int8(ctx)?"),
            Type::Octet => format!("{v}.to_uint8(ctx)?"),
            Type::Short => format!("{v}.to_int16(ctx)?"),
            Type::UnsignedShort => format!("{v}.to_uint16(ctx)?"),
            Type::Long => format!("{v}.to_i32(ctx)?"),
            Type::UnsignedLong => format!("{v}.to_u32(ctx)?"),
            Type::LongLong => format!("rt::to_i64({v}, ctx)?"),
            Type::UnsignedLongLong => format!("rt::to_u64({v}, ctx)?"),
            Type::Float | Type::Double => format!("{v}.to_number(ctx)?"),
            Type::DomString | Type::UsvString | Type::ByteString => {
                if null_to_empty {
                    format!("rt::string_from_js_null_empty({v}, ctx)?")
                } else {
                    format!("rt::string_from_js({v}, ctx)?")
                }
            }
            Type::ArrayBuffer | Type::BufferLike(_) => format!("rt::buffer_from_js({v}, ctx)?"),
            Type::Named(n) => match self.types.classify(n) {
                Named::Node => format!("rt::node_from_js({v}, I::{n}, ctx)?"),
                Named::Object => format!("rt::object_from_js({v}, I::{n}, ctx)?"),
                Named::Window => format!("rt::window_from_js({v}, ctx)?"),
                Named::EventTarget => format!("rt::event_target_from_js({v}, ctx)?"),
                Named::Dictionary | Named::Enum => {
                    format!("<web::{n} as FromJs>::from_js({v}, ctx)?")
                }
                Named::Callback => {
                    format!("rt::callback_from_js({v}, CallbackKind::Function, ctx)?")
                }
                Named::CallbackInterface => {
                    format!("rt::callback_from_js({v}, CallbackKind::Interface, ctx)?")
                }
                Named::Unknown => format!("rt::value_from_js({v}, ctx)?"),
            },
            Type::Sequence(t) | Type::FrozenArray(t) => format!(
                "rt::sequence_from_js({v}, ctx, |v, ctx| Ok({}))?",
                self.conv(t, "v", false)
            ),
            Type::Record(_, t) => format!(
                "rt::record_from_js({v}, ctx, |v, ctx| Ok({}))?",
                self.conv(t, "v", false)
            ),
            Type::Promise(_) => format!("rt::promise_from_js({v}, ctx)?"),
            Type::Union(_) => format!(
                "<web::{} as FromJs>::from_js({v}, ctx)?",
                self.types.type_label(ty)
            ),
            Type::Nullable(t) => match **t {
                Type::Any | Type::Object => format!("rt::value_from_js({v}, ctx)?"),
                _ => format!(
                    "if {v}.is_null_or_undefined() {{ None }} else {{ Some({}) }}",
                    self.conv(t, v, null_to_empty)
                ),
            },
        }
    }

    fn default_expr(&self, ty: &Type, default: &DefaultValue) -> String {
        match (ty, default) {
            (Type::Nullable(_), DefaultValue::Null) => "None".into(),
            (Type::Any | Type::Object, DefaultValue::Null) => "Value::Null".into(),
            (Type::Nullable(inner), d) => format!("Some({})", self.default_expr(inner, d)),
            (Type::Union(members), d) => {
                let label = self.types.type_label(ty);
                let pick = |pred: &dyn Fn(&Type) -> bool| members.iter().find(|m| pred(m));
                let member = match d {
                    DefaultValue::String(_) => {
                        pick(&|m| matches!(m, Type::DomString | Type::UsvString | Type::ByteString))
                    }
                    DefaultValue::Bool(_) => pick(&|m| matches!(m, Type::Boolean)),
                    DefaultValue::Int(_) | DefaultValue::Float(_) => pick(&|m| {
                        matches!(
                            m,
                            Type::Long
                                | Type::UnsignedLong
                                | Type::Double
                                | Type::Float
                                | Type::Short
                                | Type::UnsignedShort
                                | Type::LongLong
                                | Type::UnsignedLongLong
                        )
                    }),
                    DefaultValue::EmptyArray => {
                        pick(&|m| matches!(m, Type::Sequence(_) | Type::FrozenArray(_)))
                    }
                    DefaultValue::EmptyDict => pick(
                        &|m| matches!(m, Type::Named(n) if self.types.classify(n) == Named::Dictionary),
                    ),
                    DefaultValue::Null => None,
                };
                match member {
                    Some(m) => format!(
                        "web::{label}::{}({})",
                        self.types.type_label(m),
                        self.default_expr(m, d)
                    ),
                    None => {
                        format!("<web::{label} as FromJs>::from_js(&JsValue::undefined(), ctx)?")
                    }
                }
            }
            (_, DefaultValue::Bool(b)) => b.to_string(),
            (Type::Float | Type::Double, DefaultValue::Int(i)) => format!("{i}_f64"),
            (_, DefaultValue::Int(i)) => format!("({i}) as {}", self.rust_type(ty, Pos::Arg)),
            (_, DefaultValue::Float(f)) => {
                if f.is_nan() {
                    "f64::NAN".into()
                } else if f.is_infinite() {
                    if *f > 0.0 {
                        "f64::INFINITY".into()
                    } else {
                        "f64::NEG_INFINITY".into()
                    }
                } else {
                    format!("{f:?}_f64")
                }
            }
            (Type::Named(n), DefaultValue::String(s)) if self.types.classify(n) == Named::Enum => {
                format!("web::{n}::{}", variant(s))
            }
            (_, DefaultValue::String(s)) => format!("{}.to_string()", lit(s)),
            (_, DefaultValue::Null) => "Default::default()".into(),
            (_, DefaultValue::EmptyArray) => "Vec::new()".into(),
            (Type::Named(n), DefaultValue::EmptyDict) => {
                format!("<web::{n} as FromJs>::from_js(&JsValue::undefined(), ctx)?")
            }
            (_, DefaultValue::EmptyDict) => "Default::default()".into(),
        }
    }

    /// `any`/`object`, nullable or not: represented as a `Value` either way.
    fn is_any(ty: &Type) -> bool {
        match ty {
            Type::Any | Type::Object => true,
            Type::Nullable(inner) => matches!(**inner, Type::Any | Type::Object),
            _ => false,
        }
    }

    /// Statements binding `a0..aN` for an overload.
    fn arg_stmts(&self, o: &POverload) -> String {
        let mut out = String::new();
        for (i, a) in o.args.iter().enumerate() {
            let v = format!("rt::arg(args, {i})");
            if a.variadic {
                w!(
                    out,
                    "let a{i} = args.iter().skip({i}).map(|v| Ok({})).collect::<JsResult<Vec<_>>>()?;",
                    self.conv(&a.ty, "v", a.null_to_empty)
                );
            } else if a.optional {
                let present = format!("args.len() > {i} && !args[{i}].is_undefined()");
                match &a.default {
                    Some(d) => {
                        let is_dict = matches!(&a.ty, Type::Named(n) if self.types.classify(n) == Named::Dictionary);
                        if is_dict || Self::is_any(&a.ty) {
                            w!(out, "let a{i} = {};", self.conv(&a.ty, &v, a.null_to_empty));
                        } else {
                            w!(
                                out,
                                "let a{i} = if {present} {{ {} }} else {{ {} }};",
                                self.conv(&a.ty, &v, a.null_to_empty),
                                self.default_expr(&a.ty, d)
                            );
                        }
                    }
                    None => match &a.ty {
                        ty if Self::is_any(ty) => {
                            w!(out, "let a{i} = {};", self.conv(&a.ty, &v, false));
                        }
                        Type::Nullable(_) => {
                            w!(
                                out,
                                "let a{i} = if {present} {{ {} }} else {{ None }};",
                                self.conv(&a.ty, &v, a.null_to_empty)
                            );
                        }
                        Type::Named(n) if self.types.classify(n) == Named::Dictionary => {
                            w!(out, "let a{i} = {};", self.conv(&a.ty, &v, false));
                        }
                        _ => {
                            w!(
                                out,
                                "let a{i} = if {present} {{ Some({}) }} else {{ None }};",
                                self.conv(&a.ty, &v, a.null_to_empty)
                            );
                        }
                    },
                }
            } else {
                w!(out, "let a{i} = {};", self.conv(&a.ty, &v, a.null_to_empty));
            }
        }
        out
    }

    fn call_args(o: &POverload) -> String {
        (0..o.args.len()).map(|i| format!(", a{i}")).collect()
    }

    fn this_stmt(iface: &PInterface) -> String {
        match iface.handle {
            Handle::Node => format!(
                "let this = rt::this_node(this_js, I::{}, ctx)?;",
                iface.name
            ),
            Handle::Object => format!(
                "let this = rt::this_object(this_js, I::{}, ctx)?;",
                iface.name
            ),
            Handle::EventTarget => "let this = rt::this_event_target(this_js, ctx)?;".to_string(),
            Handle::Window => "rt::this_window(this_js, ctx)?;".to_string(),
        }
    }

    fn this_arg(handle: Handle) -> &'static str {
        match handle {
            Handle::Window => "",
            _ => ", this",
        }
    }

    fn target_expr(handle: Handle) -> &'static str {
        match handle {
            Handle::Node => "EventTargetRef::Node(this)",
            Handle::Object => "EventTargetRef::Object(this)",
            Handle::EventTarget => "this",
            Handle::Window => "EventTargetRef::Window",
        }
    }

    /// The type predicate used to tell overloads apart at one argument.
    fn overload_pred(&self, ty: &Type, v: &str) -> (u8, String) {
        match ty {
            Type::Nullable(t) => {
                let (rank, p) = self.overload_pred(t, v);
                (rank, format!("({v}.is_null_or_undefined() || {p})"))
            }
            Type::Named(n) => match self.types.classify(n) {
                Named::Node | Named::Object => (0, format!("rt::is_instance({v}, I::{n}, ctx)")),
                Named::Callback | Named::CallbackInterface => (1, format!("{v}.is_callable()")),
                Named::Enum => (5, "true".into()),
                _ => (4, "true".into()),
            },
            Type::Sequence(_) | Type::FrozenArray(_) => (2, format!("{v}.is_object()")),
            Type::Boolean => (3, format!("{v}.is_boolean()")),
            Type::Byte
            | Type::Octet
            | Type::Short
            | Type::UnsignedShort
            | Type::Long
            | Type::UnsignedLong
            | Type::LongLong
            | Type::UnsignedLongLong
            | Type::Float
            | Type::Double => (3, format!("{v}.is_number()")),
            Type::DomString | Type::UsvString | Type::ByteString => (5, "true".into()),
            _ => (4, "true".into()),
        }
    }

    fn overload_call(
        &self,
        iface: &PInterface,
        owner: &str,
        o: &POverload,
        is_static: bool,
        label: &str,
    ) -> String {
        let mut out = String::new();
        let min = o.min_args();
        if min > 0 {
            w!(out, "rt::require_args(args, {min}, {})?;", lit(label));
        }
        out.push_str(&self.arg_stmts(o));
        let this = if is_static || iface.kind == InterfaceKind::Namespace {
            ""
        } else {
            Self::this_arg(iface.handle)
        };
        w!(
            out,
            "let r = rt::with_cx(ctx, |cx| <Web as web::{owner}Impl>::{}(cx{this}{}));",
            o.rust,
            Self::call_args(o)
        );
        w!(out, "rt::ret(r, ctx)");
        out
    }

    fn emit_op(&self, out: &mut String, iface: &PInterface, op: &POp) {
        // A static and a regular operation may share a name (`Response.json`).
        let prefix = if op.is_static && iface.kind == InterfaceKind::Interface {
            "static_op_"
        } else {
            "op_"
        };
        let fn_name = format!("{prefix}{}", snake(&op.name).trim_end_matches('_'));
        let label = format!("{}.{}", iface.name, op.name);
        w!(
            out,
            "fn {fn_name}(this_js: &JsValue, args: &[JsValue], ctx: &mut Context) -> JsResult<JsValue> {{"
        );
        w!(out, "let _ = (this_js, args);");
        if op.stub {
            w!(out, "rt::count_stub(ctx, {});", lit(&label));
            w!(out, "let _ = ctx;\nOk(JsValue::undefined())\n}}\n");
            return;
        }
        if !op.is_static && iface.kind != InterfaceKind::Namespace {
            w!(out, "{}", Self::this_stmt(iface));
        }
        if op.overloads.len() == 1 {
            out.push_str(&self.overload_call(
                iface,
                &op.owner,
                &op.overloads[0],
                op.is_static,
                &label,
            ));
            w!(out, "}}\n");
            return;
        }
        // Overload resolution: longer signatures first, then by how specific
        // the distinguishing argument's type test is.
        let mut ranked: Vec<(usize, u8, String, &POverload)> = Vec::new();
        for (i, o) in op.overloads.iter().enumerate() {
            let mut rank = 4u8;
            let mut pred = "true".to_string();
            'find: for d in 0..o.args.len() {
                for (j, other) in op.overloads.iter().enumerate() {
                    if i == j {
                        continue;
                    }
                    if let Some(theirs) = other.args.get(d)
                        && theirs.ty != o.args[d].ty
                    {
                        let (r, p) =
                            self.overload_pred(&o.args[d].ty, &format!("rt::arg(args, {d})"));
                        rank = r;
                        pred = p;
                        break 'find;
                    }
                }
            }
            ranked.push((o.min_args(), rank, pred, o));
        }
        ranked.sort_by(|a, b| b.0.cmp(&a.0).then(a.1.cmp(&b.1)));
        for (min, _, pred, o) in &ranked {
            w!(out, "if args.len() >= {min} && {pred} {{");
            out.push_str(&self.overload_call(iface, &op.owner, o, op.is_static, &label));
            w!(out, "}} else");
        }
        w!(
            out,
            "{{ Err(rt::type_error({})) }}",
            lit(&format!("{label}: no overload matches the arguments"))
        );
        w!(out, "}}\n");
    }

    fn reflect_default(default: &Option<String>, fallback: &str) -> String {
        default.clone().unwrap_or_else(|| fallback.to_string())
    }

    fn emit_attr(&self, out: &mut String, iface: &PInterface, a: &PAttr) {
        let base = a.rust.trim_end_matches('_').to_string();
        let label = format!("{}.{}", iface.name, a.name);
        let this_stmt = if a.is_static || iface.kind == InterfaceKind::Namespace {
            String::new()
        } else {
            Self::this_stmt(iface)
        };
        let this_arg = if a.is_static || iface.kind == InterfaceKind::Namespace {
            ""
        } else {
            Self::this_arg(iface.handle)
        };

        // Getter.
        w!(
            out,
            "fn get_{base}(this_js: &JsValue, _args: &[JsValue], ctx: &mut Context) -> JsResult<JsValue> {{"
        );
        match &a.kind {
            AttrKind::Stub => {
                w!(
                    out,
                    "rt::count_stub(ctx, {});\nlet _ = this_js;\nOk(JsValue::undefined())",
                    lit(&label)
                );
            }
            AttrKind::EventHandler => {
                w!(out, "{this_stmt}");
                w!(
                    out,
                    "let r = rt::with_cx(ctx, |cx| catpaw_web::events::event_handler(cx, {}, {}));",
                    Self::target_expr(iface.handle),
                    lit(a.name.trim_start_matches("on"))
                );
                w!(out, "rt::ret(r, ctx)");
            }
            AttrKind::Reflect(r) => {
                if r.kind == ReflectKind::TokenList {
                    w!(
                        out,
                        "if let Some(v) = rt::cached(this_js, {}, ctx) {{ return Ok(v); }}",
                        lit(&a.name)
                    );
                }
                w!(out, "{this_stmt}");
                let attr = lit(&r.attr);
                let call = match r.kind {
                    ReflectKind::String => {
                        format!("catpaw_web::reflect::get_string(cx, this, {attr})")
                    }
                    ReflectKind::NullableString => {
                        format!("catpaw_web::reflect::get_nullable_string(cx, this, {attr})")
                    }
                    ReflectKind::Bool => format!("catpaw_web::reflect::get_bool(cx, this, {attr})"),
                    ReflectKind::Long => format!(
                        "catpaw_web::reflect::get_long(cx, this, {attr}, {}, {})",
                        Self::reflect_default(&r.default, "0"),
                        lit(r.limit)
                    ),
                    ReflectKind::UnsignedLong => format!(
                        "catpaw_web::reflect::get_unsigned_long(cx, this, {attr}, {}, {})",
                        Self::reflect_default(&r.default, "0"),
                        lit(r.limit)
                    ),
                    ReflectKind::Double => format!(
                        "catpaw_web::reflect::get_double(cx, this, {attr}, {}_f64, {})",
                        Self::reflect_default(&r.default, "0.0"),
                        lit(r.limit)
                    ),
                    ReflectKind::Url => format!("catpaw_web::reflect::get_url(cx, this, {attr})"),
                    ReflectKind::TokenList => {
                        format!("catpaw_web::reflect::get_token_list(cx, this, {attr})")
                    }
                };
                w!(out, "let r = rt::with_cx(ctx, |cx| {call});");
                if r.kind == ReflectKind::TokenList {
                    w!(
                        out,
                        "let v = rt::ret(r, ctx)?;\nrt::cache(this_js, {}, &v, ctx);\nOk(v)",
                        lit(&a.name)
                    );
                } else {
                    w!(out, "rt::ret(r, ctx)");
                }
            }
            AttrKind::Native => {
                if a.same_object {
                    w!(
                        out,
                        "if let Some(v) = rt::cached(this_js, {}, ctx) {{ return Ok(v); }}",
                        lit(&a.name)
                    );
                }
                w!(out, "{this_stmt}");
                w!(
                    out,
                    "let r = rt::with_cx(ctx, |cx| <Web as web::{}Impl>::{}(cx{this_arg}));",
                    a.owner,
                    a.rust
                );
                if a.same_object {
                    w!(
                        out,
                        "let v = rt::ret(r, ctx)?;\nrt::cache(this_js, {}, &v, ctx);\nOk(v)",
                        lit(&a.name)
                    );
                } else if a.undefined_when_absent {
                    w!(
                        out,
                        "let v = rt::ret(r, ctx)?;\nOk(if v.is_null() {{ JsValue::undefined() }} else {{ v }})"
                    );
                } else {
                    w!(out, "rt::ret(r, ctx)");
                }
            }
        }
        w!(out, "}}\n");

        // Setter.
        let has_setter = !a.readonly || a.put_forwards.is_some() || a.replaceable;
        if !has_setter {
            return;
        }
        w!(
            out,
            "fn set_{base}(this_js: &JsValue, args: &[JsValue], ctx: &mut Context) -> JsResult<JsValue> {{"
        );
        if a.readonly {
            if let Some(target) = &a.put_forwards {
                w!(
                    out,
                    "rt::put_forwards(this_js, {}, {}, rt::arg(args, 0), ctx)?;",
                    lit(&a.name),
                    lit(target)
                );
            } else {
                w!(
                    out,
                    "rt::replace_property(this_js, {}, rt::arg(args, 0), ctx)?;",
                    lit(&a.name)
                );
            }
            w!(out, "Ok(JsValue::undefined())\n}}\n");
            return;
        }
        match &a.kind {
            AttrKind::Stub => {
                w!(
                    out,
                    "rt::count_stub(ctx, {});\nlet _ = (this_js, args);",
                    lit(&label)
                );
            }
            AttrKind::EventHandler => {
                w!(out, "{this_stmt}");
                w!(
                    out,
                    "let a0 = rt::event_handler_from_js(rt::arg(args, 0), ctx)?;"
                );
                w!(
                    out,
                    "let r = rt::with_cx(ctx, |cx| catpaw_web::events::set_event_handler(cx, {}, {}, a0));",
                    Self::target_expr(iface.handle),
                    lit(a.name.trim_start_matches("on"))
                );
                w!(out, "rt::ret(r, ctx)?;");
            }
            AttrKind::Reflect(r) => {
                w!(out, "{this_stmt}");
                let attr = lit(&r.attr);
                let v = "rt::arg(args, 0)";
                let (conv, call) = match r.kind {
                    ReflectKind::String | ReflectKind::Url => (
                        self.conv(&Type::DomString, v, a.null_to_empty),
                        format!("catpaw_web::reflect::set_string(cx, this, {attr}, a0)"),
                    ),
                    ReflectKind::NullableString => (
                        self.conv(&Type::Nullable(Box::new(Type::DomString)), v, false),
                        format!("catpaw_web::reflect::set_nullable_string(cx, this, {attr}, a0)"),
                    ),
                    ReflectKind::Bool => (
                        self.conv(&Type::Boolean, v, false),
                        format!("catpaw_web::reflect::set_bool(cx, this, {attr}, a0)"),
                    ),
                    ReflectKind::Long => (
                        self.conv(&Type::Long, v, false),
                        format!(
                            "catpaw_web::reflect::set_long(cx, this, {attr}, a0, {})",
                            lit(r.limit)
                        ),
                    ),
                    ReflectKind::UnsignedLong => (
                        self.conv(&Type::UnsignedLong, v, false),
                        format!(
                            "catpaw_web::reflect::set_unsigned_long(cx, this, {attr}, a0, {}, {})",
                            Self::reflect_default(&r.default, "0"),
                            lit(r.limit)
                        ),
                    ),
                    ReflectKind::Double => (
                        self.conv(&Type::Double, v, false),
                        format!(
                            "catpaw_web::reflect::set_double(cx, this, {attr}, a0, {})",
                            lit(r.limit)
                        ),
                    ),
                    ReflectKind::TokenList => unreachable!("token lists are readonly"),
                };
                w!(out, "let a0 = {conv};");
                w!(
                    out,
                    "let r = rt::with_cx(ctx, |cx| {call});\nrt::ret(r, ctx)?;"
                );
            }
            AttrKind::Native => {
                w!(out, "{this_stmt}");
                match &a.ty {
                    // Assigning a string that is not one of the enumeration's
                    // values is ignored rather than an error.
                    Type::Named(n) if self.types.classify(n) == Named::Enum => {
                        w!(
                            out,
                            "let s = rt::string_from_js(rt::arg(args, 0), ctx)?;\nlet Some(a0) = web::{n}::parse(&s) else {{ return Ok(JsValue::undefined()); }};"
                        );
                    }
                    _ => w!(
                        out,
                        "let a0 = {};",
                        self.conv(&a.ty, "rt::arg(args, 0)", a.null_to_empty)
                    ),
                }
                w!(
                    out,
                    "let r = rt::with_cx(ctx, |cx| <Web as web::{}Impl>::set_{base}(cx{this_arg}, a0));\nrt::ret(r, ctx)?;",
                    a.owner
                );
            }
        }
        w!(out, "Ok(JsValue::undefined())\n}}\n");
    }

    fn emit_constructor(&self, out: &mut String, iface: &PInterface) {
        let Some(overloads) = &iface.constructor else {
            return;
        };
        let label = format!("{} constructor", iface.name);
        w!(
            out,
            "fn ctor(new_target: &JsValue, args: &[JsValue], ctx: &mut Context) -> JsResult<JsValue> {{"
        );
        w!(out, "rt::require_new(new_target, {})?;", lit(&iface.name));
        let wrap = match iface.handle {
            Handle::Node => "rt::wrap_constructed_node",
            _ => "rt::wrap_constructed_object",
        };
        let mut ranked: Vec<&POverload> = overloads.iter().collect();
        ranked.sort_by_key(|o| std::cmp::Reverse(o.min_args()));
        for (idx, o) in ranked.iter().enumerate() {
            let last = idx + 1 == ranked.len();
            if !last {
                w!(out, "if args.len() >= {} {{", o.min_args());
            }
            let min = o.min_args();
            if min > 0 {
                w!(out, "rt::require_args(args, {min}, {})?;", lit(&label));
            }
            out.push_str(&self.arg_stmts(o));
            w!(
                out,
                "let r = rt::with_cx(ctx, |cx| <Web as web::{}Impl>::{}(cx{}));",
                iface.name,
                o.rust,
                Self::call_args(o)
            );
            w!(out, "let id = r.map_err(|e| rt::exception_to_js(e, ctx))?;");
            w!(
                out,
                "return {wrap}(id, new_target, I::{}, ctx);",
                iface.name
            );
            if !last {
                w!(out, "}}");
            }
        }
        w!(out, "}}\n");
    }

    fn emit_exotic(&self, out: &mut String, iface: &PInterface) -> String {
        let Some(e) = &iface.exotic else {
            return "None".into();
        };
        let handle = match iface.handle {
            Handle::Node => "h.node()",
            _ => "h.object()",
        };
        let name = &iface.name;
        // A special operation may be inherited: its implementation is then
        // on the trait of the interface that declares it.
        let owner = |special: &Option<crate::plan::PSpecial>| {
            special
                .as_ref()
                .map(|s| s.owner.clone())
                .unwrap_or_else(|| name.clone())
        };
        let indexed_owner = owner(&e.indexed_getter);
        let named_owner = owner(&e.named_getter);
        let setter_owner = owner(&e.named_setter);
        let deleter_owner = owner(&e.named_deleter);
        let mut fields = Vec::new();
        if e.indexed_getter.is_some() {
            w!(
                out,
                "fn exotic_length(h: rt::Handle, ctx: &mut Context) -> JsResult<u32> {{\nlet this = {handle};\nlet r = rt::with_cx(ctx, |cx| <Web as web::{indexed_owner}Impl>::length(cx, this));\nr.map_err(|e| rt::exception_to_js(e, ctx))\n}}\n"
            );
            w!(
                out,
                "fn exotic_indexed_get(h: rt::Handle, index: u32, ctx: &mut Context) -> JsResult<Option<JsValue>> {{\nlet this = {handle};\nlet r = rt::with_cx(ctx, |cx| <Web as web::{indexed_owner}Impl>::indexed_get(cx, this, index));\nrt::ret_opt(r, ctx)\n}}\n"
            );
            fields.push(
                "length: Some(exotic_length), indexed_get: Some(exotic_indexed_get)".to_string(),
            );
        } else {
            fields.push("length: None, indexed_get: None".to_string());
        }
        if e.named_getter.is_some() {
            w!(
                out,
                "fn exotic_named_get(h: rt::Handle, name: &str, ctx: &mut Context) -> JsResult<Option<JsValue>> {{\nlet this = {handle};\nlet r = rt::with_cx(ctx, |cx| <Web as web::{named_owner}Impl>::named_get(cx, this, name));\nrt::ret_opt(r, ctx)\n}}\n"
            );
            w!(
                out,
                "fn exotic_named_properties(h: rt::Handle, ctx: &mut Context) -> JsResult<Vec<String>> {{\nlet this = {handle};\nlet r = rt::with_cx(ctx, |cx| <Web as web::{named_owner}Impl>::named_properties(cx, this));\nr.map_err(|e| rt::exception_to_js(e, ctx))\n}}\n"
            );
            fields.push("named_get: Some(exotic_named_get), named_properties: Some(exotic_named_properties)".to_string());
        } else {
            fields.push("named_get: None, named_properties: None".to_string());
        }
        if let Some(s) = &e.named_setter {
            w!(
                out,
                "fn exotic_named_set(h: rt::Handle, name: &str, value: &JsValue, ctx: &mut Context) -> JsResult<()> {{\nlet this = {handle};\nlet a0 = {};\nlet r = rt::with_cx(ctx, |cx| <Web as web::{setter_owner}Impl>::named_set(cx, this, name, a0));\nr.map_err(|e| rt::exception_to_js(e, ctx))\n}}\n",
                self.conv(&s.ty, "value", s.null_to_empty)
            );
            fields.push("named_set: Some(exotic_named_set)".to_string());
        } else {
            fields.push("named_set: None".to_string());
        }
        if e.named_deleter.is_some() {
            w!(
                out,
                "fn exotic_named_delete(h: rt::Handle, name: &str, ctx: &mut Context) -> JsResult<bool> {{\nlet this = {handle};\nlet r = rt::with_cx(ctx, |cx| <Web as web::{deleter_owner}Impl>::named_delete(cx, this, name));\nr.map_err(|e| rt::exception_to_js(e, ctx))\n}}\n"
            );
            fields.push("named_delete: Some(exotic_named_delete)".to_string());
        } else {
            fields.push("named_delete: None".to_string());
        }
        fields.push(format!(
            "override_builtins: {}",
            self.idl
                .interfaces
                .get(name)
                .is_some_and(|i| i.ext.has("LegacyOverrideBuiltIns"))
        ));
        fields.push(format!(
            "attribute_like: {}",
            self.idl
                .interfaces
                .get(name)
                .is_some_and(|i| i.ext.has("CatPawNamedPropertiesAreAttributes"))
        ));
        format!("Some(rt::ExoticDef {{ {} }})", fields.join(", "))
    }

    fn emit_interface(&self, out: &mut String, iface: &PInterface) {
        let module = snake(&iface.name);
        w!(out, "pub mod {module} {{\nuse super::*;\n");

        for a in &iface.attrs {
            self.emit_attr(out, iface, a);
        }
        for op in &iface.ops {
            self.emit_op(out, iface, op);
        }
        self.emit_constructor(out, iface);

        // Stringifier.
        let mut to_string = None;
        match &iface.stringifier {
            Some(Stringifier::Attribute(attr)) => {
                if let Some(a) = iface.attrs.iter().find(|a| a.name == *attr) {
                    to_string = Some(format!("get_{}", a.rust.trim_end_matches('_')));
                }
            }
            Some(Stringifier::Method) => {
                w!(
                    out,
                    "fn op_to_string(this_js: &JsValue, _args: &[JsValue], ctx: &mut Context) -> JsResult<JsValue> {{"
                );
                w!(out, "{}", Self::this_stmt(iface));
                w!(
                    out,
                    "let r = rt::with_cx(ctx, |cx| <Web as web::{}Impl>::stringify(cx{}));\nrt::ret(r, ctx)\n}}\n",
                    iface.name,
                    Self::this_arg(iface.handle)
                );
                to_string = Some("op_to_string".to_string());
            }
            None => {}
        }

        // Pair iterator source.
        let mut iterable = "rt::Iterable::None".to_string();
        match &iface.iterable {
            Some((None, _)) => iterable = "rt::Iterable::Values".to_string(),
            Some((Some(_), _)) => {
                w!(
                    out,
                    "fn iterate(this_js: &JsValue, _args: &[JsValue], ctx: &mut Context) -> JsResult<JsValue> {{"
                );
                w!(out, "{}", Self::this_stmt(iface));
                w!(
                    out,
                    "let r = rt::with_cx(ctx, |cx| <Web as web::{}Impl>::iterate(cx{}));\nrt::ret_pairs(r, ctx)\n}}\n",
                    iface.name,
                    Self::this_arg(iface.handle)
                );
                iterable = "rt::Iterable::Pairs(iterate)".to_string();
            }
            None => {}
        }

        let exotic = self.emit_exotic(out, iface);

        // Tables.
        let attr_entry = |a: &PAttr| {
            let base = a.rust.trim_end_matches('_');
            let setter = if !a.readonly || a.put_forwards.is_some() || a.replaceable {
                format!("Some(set_{base})")
            } else {
                "None".to_string()
            };
            format!(
                "rt::AttrDef {{ name: {}, getter: get_{base}, setter: {setter} }}",
                lit(&a.name)
            )
        };
        let op_entry = |o: &POp| {
            let length = o
                .overloads
                .iter()
                .map(POverload::min_args)
                .min()
                .unwrap_or(0);
            format!(
                "rt::OpDef {{ name: {}, func: {}op_{}, length: {length} }}",
                lit(&o.name),
                if o.is_static { "static_" } else { "" },
                snake(&o.name).trim_end_matches('_')
            )
        };
        let mut ops: Vec<String> = iface
            .ops
            .iter()
            .filter(|o| !o.is_static)
            .map(op_entry)
            .collect();
        if let Some(f) = &to_string
            && !iface.ops.iter().any(|o| o.name == "toString")
        {
            ops.push(format!(
                "rt::OpDef {{ name: \"toString\", func: {f}, length: 0 }}"
            ));
        }
        let static_ops: Vec<String> = iface
            .ops
            .iter()
            .filter(|o| o.is_static)
            .map(op_entry)
            .collect();
        let attrs: Vec<String> = iface
            .attrs
            .iter()
            .filter(|a| !a.is_static)
            .map(attr_entry)
            .collect();
        let static_attrs: Vec<String> = iface
            .attrs
            .iter()
            .filter(|a| a.is_static)
            .map(attr_entry)
            .collect();
        let consts: Vec<String> = iface
            .consts
            .iter()
            .filter_map(|(n, v)| {
                let value = match v {
                    ConstValue::Int(i) => format!("{i}_f64"),
                    ConstValue::Float(f) => format!("{f:?}_f64"),
                    _ => return None,
                };
                Some(format!("({}, {value})", lit(n)))
            })
            .collect();

        w!(
            out,
            "pub static DEF: rt::InterfaceDef = rt::InterfaceDef {{"
        );
        w!(out, "    id: I::{},", iface.name);
        w!(out, "    name: {},", lit(&iface.name));
        match &iface.parent {
            Some(p) => w!(out, "    parent: Some(I::{p}),"),
            None => w!(out, "    parent: None,"),
        }
        w!(out, "    global: {},", iface.global);
        match &iface.constructor {
            Some(o) => w!(
                out,
                "    constructor: Some(ctor),\n    constructor_length: {},",
                o.iter().map(POverload::min_args).min().unwrap_or(0)
            ),
            None => w!(out, "    constructor: None,\n    constructor_length: 0,"),
        }
        w!(out, "    attrs: &[{}],", attrs.join(", "));
        w!(out, "    ops: &[{}],", ops.join(", "));
        w!(out, "    static_attrs: &[{}],", static_attrs.join(", "));
        w!(out, "    static_ops: &[{}],", static_ops.join(", "));
        w!(out, "    consts: &[{}],", consts.join(", "));
        w!(out, "    iterable: {iterable},");
        w!(out, "    exotic: {exotic},");
        w!(out, "}};\n}}\n");
    }

    fn emit_namespace(&self, out: &mut String, ns: &PInterface) {
        let module = format!("ns_{}", snake(&ns.name));
        w!(out, "pub mod {module} {{\nuse super::*;\n");
        for a in &ns.attrs {
            self.emit_attr(out, ns, a);
        }
        for op in &ns.ops {
            self.emit_op(out, ns, op);
        }
        let ops: Vec<String> = ns
            .ops
            .iter()
            .map(|o| {
                format!(
                    "rt::OpDef {{ name: {}, func: op_{}, length: {} }}",
                    lit(&o.name),
                    snake(&o.name).trim_end_matches('_'),
                    o.overloads
                        .iter()
                        .map(POverload::min_args)
                        .min()
                        .unwrap_or(0)
                )
            })
            .collect();
        w!(
            out,
            "pub static DEF: rt::NamespaceDef = rt::NamespaceDef {{ name: {}, ops: &[{}] }};\n}}\n",
            lit(&ns.name),
            ops.join(", ")
        );
    }

    fn emit_enum_conv(&self, out: &mut String, name: &str) {
        w!(
            out,
            "impl FromJs for web::{name} {{\nfn from_js(v: &JsValue, ctx: &mut Context) -> JsResult<Self> {{\nlet s = rt::string_from_js(v, ctx)?;\nweb::{name}::parse(&s).ok_or_else(|| rt::type_error(&format!(\"'{{s}}' is not a valid {name}\")))\n}}\n}}\n"
        );
        w!(
            out,
            "impl IntoJs for web::{name} {{\nfn into_js(self, ctx: &mut Context) -> JsResult<JsValue> {{\nself.as_str().into_js(ctx)\n}}\n}}\n"
        );
    }

    fn emit_dictionary_conv(&self, out: &mut String, name: &str) {
        let members = self.dictionary_members(name);
        w!(
            out,
            "impl FromJs for web::{name} {{\nfn from_js(v: &JsValue, ctx: &mut Context) -> JsResult<Self> {{\nlet obj = rt::dictionary_object(v, {})?;\nOk(Self {{",
            lit(name)
        );
        for (n, ty, required, default) in &members {
            let field = snake(n);
            let conv = self.conv(ty, "(&m)", false);
            let is_dict =
                matches!(ty, Type::Named(d) if self.types.classify(d) == Named::Dictionary);
            let missing = if *required {
                format!(
                    "return Err(rt::type_error({}))",
                    lit(&format!("{name}.{n} is required"))
                )
            } else if let Some(d) = default {
                self.default_expr(ty, d)
            } else if is_dict {
                format!(
                    "<web::{} as FromJs>::from_js(&JsValue::undefined(), ctx)?",
                    self.types.type_label(ty)
                )
            } else if Self::is_any(ty) {
                "Value::Undefined".to_string()
            } else {
                "None".to_string()
            };
            let wrap_some = !*required
                && default.is_none()
                && !is_dict
                && !Self::is_any(ty)
                && !matches!(ty, Type::Nullable(_));
            let present = if wrap_some {
                format!("Some({conv})")
            } else {
                conv
            };
            w!(
                out,
                "{field}: match rt::dictionary_member(&obj, {}, ctx)? {{ Some(m) => {present}, None => {missing} }},",
                lit(n)
            );
        }
        w!(out, "}})\n}}\n}}\n");

        w!(
            out,
            "impl IntoJs for web::{name} {{\nfn into_js(self, ctx: &mut Context) -> JsResult<JsValue> {{\nlet obj = rt::new_plain_object(ctx);"
        );
        for (n, _, _, _) in &members {
            w!(
                out,
                "rt::set_member(&obj, {}, self.{}, ctx)?;",
                lit(n),
                snake(n)
            );
        }
        w!(out, "Ok(obj.into())\n}}\n}}\n");
    }

    fn emit_union_conv(&self, out: &mut String, label: &str, members: &[Type]) {
        w!(
            out,
            "impl FromJs for web::{label} {{\nfn from_js(v: &JsValue, ctx: &mut Context) -> JsResult<Self> {{"
        );
        let find = |pred: &dyn Fn(&Type) -> bool| members.iter().find(|m| pred(m));
        let var = |m: &Type| format!("web::{label}::{}", self.types.type_label(m));
        // 1. Platform objects.
        for m in members {
            if let Type::Named(n) = m {
                match self.types.classify(n) {
                    Named::Node => w!(
                        out,
                        "if rt::is_instance(v, I::{n}, ctx) {{ return Ok({}(rt::node_from_js(v, I::{n}, ctx)?)); }}",
                        var(m)
                    ),
                    Named::Object => w!(
                        out,
                        "if rt::is_instance(v, I::{n}, ctx) {{ return Ok({}(rt::object_from_js(v, I::{n}, ctx)?)); }}",
                        var(m)
                    ),
                    Named::Window => w!(
                        out,
                        "if rt::is_window(v, ctx) {{ return Ok({}(WindowRef)); }}",
                        var(m)
                    ),
                    Named::EventTarget => w!(
                        out,
                        "if let Ok(t) = rt::event_target_from_js(v, ctx) {{ return Ok({}(t)); }}",
                        var(m)
                    ),
                    _ => {}
                }
            }
        }
        // 2. Buffers.
        if let Some(m) = find(&|m| matches!(m, Type::ArrayBuffer | Type::BufferLike(_))) {
            w!(
                out,
                "if rt::is_buffer(v) {{ return Ok({}(rt::buffer_from_js(v, ctx)?)); }}",
                var(m)
            );
        }
        // 3. Callables.
        if let Some(m) = find(
            &|m| matches!(m, Type::Named(n) if matches!(self.types.classify(n), Named::Callback | Named::CallbackInterface)),
        ) {
            w!(
                out,
                "if v.is_callable() {{ return Ok({}({})); }}",
                var(m),
                self.conv(m, "v", false)
            );
        }
        // 4. Other objects: sequence, then dictionary/record/object.
        if let Some(m) = find(&|m| matches!(m, Type::Sequence(_) | Type::FrozenArray(_))) {
            w!(
                out,
                "if rt::is_iterable(v, ctx)? {{ return Ok({}({})); }}",
                var(m),
                self.conv(m, "v", false)
            );
        }
        let dict_like = find(&|m| {
            matches!(m, Type::Record(..) | Type::Object)
                || matches!(m, Type::Named(n) if self.types.classify(n) == Named::Dictionary)
        });
        if let Some(m) = dict_like {
            w!(
                out,
                "if v.is_object() || v.is_null_or_undefined() {{ return Ok({}({})); }}",
                var(m),
                self.conv(m, "v", false)
            );
        }
        // 5. Primitives.
        if let Some(m) = find(&|m| matches!(m, Type::Boolean)) {
            w!(
                out,
                "if v.is_boolean() {{ return Ok({}(v.to_boolean())); }}",
                var(m)
            );
        }
        let numeric = find(&|m| {
            matches!(
                m,
                Type::Byte
                    | Type::Octet
                    | Type::Short
                    | Type::UnsignedShort
                    | Type::Long
                    | Type::UnsignedLong
                    | Type::LongLong
                    | Type::UnsignedLongLong
                    | Type::Float
                    | Type::Double
            )
        });
        if let Some(m) = numeric {
            w!(
                out,
                "if v.is_number() {{ return Ok({}({})); }}",
                var(m),
                self.conv(m, "v", false)
            );
        }
        let string = find(&|m| matches!(m, Type::DomString | Type::UsvString | Type::ByteString));
        let enumeration =
            find(&|m| matches!(m, Type::Named(n) if self.types.classify(n) == Named::Enum));
        if let Some(m) = string {
            w!(out, "Ok({}(rt::string_from_js(v, ctx)?))", var(m));
        } else if let Some(m) = enumeration {
            w!(out, "Ok({}({}))", var(m), self.conv(m, "v", false));
        } else if let Some(m) = numeric {
            w!(out, "Ok({}({}))", var(m), self.conv(m, "v", false));
        } else if let Some(m) = find(&|m| matches!(m, Type::Boolean)) {
            w!(out, "Ok({}(v.to_boolean()))", var(m));
        } else if let Some(m) = find(&|m| matches!(m, Type::Any)) {
            w!(out, "Ok({}(rt::value_from_js(v, ctx)?))", var(m));
        } else {
            w!(
                out,
                "Err(rt::type_error({}))",
                lit(&format!("value is not convertible to {label}"))
            );
        }
        w!(out, "}}\n}}\n");

        w!(
            out,
            "impl IntoJs for web::{label} {{\nfn into_js(self, ctx: &mut Context) -> JsResult<JsValue> {{\nmatch self {{"
        );
        for m in members {
            w!(out, "{}(v) => v.into_js(ctx),", var(m));
        }
        w!(out, "}}\n}}\n}}\n");
    }

    pub fn emit_boa(&self) -> String {
        let mut out = String::new();
        out.push_str(HEADER);
        out.push_str(
            "#![allow(unused_variables, unused_imports, unused_parens, unused_comparisons, unreachable_code, clippy::all)]\n\nuse boa_engine::{Context, JsResult, JsValue};\nuse catpaw_js::{CallbackKind, EventTargetRef, Value, WindowRef};\nuse catpaw_web::Web;\nuse catpaw_web::generated as web;\nuse catpaw_web::generated::InterfaceId as I;\n\nuse crate::rt::{self, FromJs, IntoJs};\n\n",
        );
        for name in &self.plan.enums {
            self.emit_enum_conv(&mut out, name);
        }
        for name in &self.plan.dictionaries {
            self.emit_dictionary_conv(&mut out, name);
        }
        for u in &self.plan.unions {
            self.emit_union_conv(&mut out, &u.name, &u.members);
        }
        for iface in &self.plan.interfaces {
            self.emit_interface(&mut out, iface);
        }
        for ns in &self.plan.namespaces {
            self.emit_namespace(&mut out, ns);
        }
        w!(
            out,
            "/// Interface definitions, parents before children.\npub static INTERFACES: &[&rt::InterfaceDef] = &["
        );
        for iface in &self.plan.interfaces {
            w!(out, "    &{}::DEF,", snake(&iface.name));
        }
        w!(out, "];\n");
        w!(out, "pub static NAMESPACES: &[&rt::NamespaceDef] = &[");
        for ns in &self.plan.namespaces {
            w!(out, "    &ns_{}::DEF,", snake(&ns.name));
        }
        w!(out, "];");
        out
    }
}
