[package]
name = "catpaw-webidl"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "CatPaw browser engine: webidl"

[dependencies]
weedle = { package = "weedle2", version = "5" }
anyhow.workspace = true
serde.workspace = true
toml = "0.9"
