[package]
name = "catpaw-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "CatPaw browser engine: web"

[dependencies]
getrandom.workspace = true
sha1 = { workspace = true, features = ["oid"] }
sha2 = { workspace = true, features = ["oid"] }
catpaw-dom = { path = "../catpaw-dom", version = "0.0.1" }
catpaw-js = { path = "../catpaw-js", version = "0.0.1" }
catpaw-style = { path = "../catpaw-style", version = "0.0.1" }
catpaw-layout = { path = "../catpaw-layout", version = "0.0.1" }
catpaw-text = { path = "../catpaw-text", version = "0.0.1" }
catpaw-paint = { path = "../catpaw-paint", version = "0.0.1" }
base64.workspace = true
encoding_rs.workspace = true
indexmap.workspace = true
serde_json.workspace = true
slotmap.workspace = true
url.workspace = true
hmac = "0.12"
aes-gcm = "0.10"
aes = "0.8"
cbc = "0.1"
ctr = "0.9"
pbkdf2 = "0.12"
hkdf = "0.12"
x25519-dalek = { version = "2", features = ["static_secrets"] }
p256 = { version = "0.13", features = ["ecdsa", "ecdh", "pkcs8"] }
p384 = { version = "0.13", features = ["ecdsa", "ecdh", "pkcs8"] }
rsa = { version = "0.9", features = ["sha2"] }
ed25519-dalek = { workspace = true, features = ["pkcs8", "rand_core"] }
rand = "0.8"
cipher = { version = "0.4", features = ["alloc", "block-padding"] }
ecdsa = { version = "0.16", features = ["hazmat", "signing", "verifying"] }
