[package]
name = "catpaw-web"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish = false
description = "CatPaw browser engine: web"

[dependencies]
getrandom.workspace = true
sha1.workspace = true
sha2.workspace = true
catpaw-dom = { path = "../catpaw-dom", version = "0.0.1" }
catpaw-js = { path = "../catpaw-js", version = "0.0.1" }
catpaw-style = { path = "../catpaw-style", version = "0.0.1" }
base64.workspace = true
encoding_rs.workspace = true
indexmap.workspace = true
serde_json.workspace = true
slotmap.workspace = true
url.workspace = true
